FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc build-essential git && rm -rf /var/lib/apt/lists/*

COPY service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir \
      "git+https://github.com/kotateja/WeAreChecking-FastF1.git@main#egg=flin"

COPY service /app/service
COPY feature_repo /app/feature_repo
ENV FEAST_REPO=/app/feature_repo
CMD ["uvicorn", "service.app:app", "--host", "0.0.0.0", "--port", "8000"]
