FROM apache/airflow:2.8.1-python3.9
USER root
RUN apt-get update &&     apt-get install -y --no-install-recommends     build-essential &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.airflow.txt /requirements.airflow.txt
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r /requirements.airflow.txt
