services:

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  feast-online:
    image: redis:7-alpine   # re-use Redis
    depends_on: [redis]

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    command: mlflow server --backend-store-uri /mlflow --host 0.0.0.0
    volumes: ["./mlruns:/mlflow"]
    ports: ["5000:5000"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    environment:
      - FEAST_REPO=/app/feature_repo
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports: ["8000:8000"]
    depends_on: [mlflow, redis]

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      - FEAST_REPO=/app/feature_repo
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports: ["8080:8080"]
    depends_on: [redis, mlflow]

  prometheus:
    image: prom/prometheus:latest
    volumes: ["./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    depends_on: [prometheus]

networks: {default: {}}
